[project]
name = "backend"
version = "0.1.0"
description = "backend for chat"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika>=1.3.2",
    "pydantic>=2.10.2",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]
